### PR TITLE
feat(audio-formats): use pyav to support more file formats

### LINKED ISSUE #18: add support of other audio formats
Using the pyav package would allow to support more audio formats that just wav single channel at 16khz.

### PR DESCRIPTION
**Pull request by mlaradji**
This resolves #18. The file conversion is done on-the-fly through PyAV.

### Known Limitations
- ~Currently, only the first audio channel is used. It's unclear to me how to combine multiple channel audio into the format that DeepSpeech expects.~ I was mistaken. Only the first audio _stream_ is used (which might have multiple channels). 
- The audio is converted to a numpy array using pyav. This conversion has room for improvement. For example, we can initialize a numpy array of the right size before the resampling. This would save memory and cpu time.

~Note that this change has not been tested extensively yet.~

### CODE REVIEW

**Review by MainRo — CHANGES_REQUESTED** [review]
Thank you for the PR !
Can you remove the poetry part ? packaging is already done and automated, and weak dependencies are easier to manage here. Are all these hash in requirements.txt from poetry also ?
What is the need for the replacement of type by isinstance ? All types are namedtuple and they are hardly inheritable. This is why I used type checking. Unless you have a use case for this, please remove this commit also.

Concerning the decoding, and number of channel. There is an example here where I downsample to mono, and use the first stream of the media:
https://github.com/MainRo/deep-speaker/blob/master/deep_speaker/toolbox/audio_codec.py#L7

BTW, this feature should be embedded in a function/module with a fallback to scipy decoding if pyav is not installed (e.g. windows or macos installations). I can work on this after merging your changes if you want, putting the decoding part in a dedicated module.

**Comment by mlaradji** [comment]
@MainRo I have removed the poetry part. I personally find it (or `pipenv`) indispensable, but it is up to style. The hashes were from poetry.
The `isinstance` is unnecessary. I thought `isinstance` and `type` are interchangeable, but like you mentioned `isinstance` checks for inheritance. We only need identity.

I removed both commits as requested. I've separated the decoding into a module and added a fallback to `scipy`.

I have tested the changes and it looks like the PR is ready for review.

**Review by MainRo — CHANGES_REQUESTED** [review]
Thanks that's great !
Just one last removal request: Please remove type hinting. The short reason for this is that - for now - I consider that it the added constraints are not worth the benefits.

**Comment by mlaradji** [comment]
@MainRo I've made the changes.

Type hints don't do anything at runtime, so I'm not sure what you mean by constraints (though they do mean python2 is no longer supported). Is it for doc purposes; we want to keep the option open to support more general types in those functions?

**Comment by mlaradji** [comment]
~Looks like `wav` files are not being read properly (but mp3 files are fine). I'm debugging this now~ 

Looks like it was an issue with my setup; `deepspeech-server` looks fine. Sorry about the false alarm.

**Comment by MainRo** [comment]
> @MainRo I've made the changes.
> 
> Type hints don't do anything at runtime, so I'm not sure what you mean by constraints (though they do mean python2 is no longer supported). Is it for doc purposes; we want to keep the option open to support more general types in those functions?

here is the longer explanation :)

My point is that a big part of what makes python appealing is that it is a dynamically typed language. With type hinting you restrict you code to be statically typed (rather you fool yourself, because nothing is enforced). There are many cases where dynamic type simplify the code. I am ready to "pay" for more complex code with statically typed  languages because there is the huge performance gain: They are all compiled languages, most without interpreter at runtime.
Moreover when I read type hinted code, I see many situations where type hints are only partially used. This should probably be solved with generics I guess, but it is not always the case.
So for now I see it only as a way to better document functions. I would expect that statically typed functions have some runtime optimizations to improve performance. Maybe this will be the case in the future.

**Review by MainRo — APPROVED** [review]

**Comment by mlaradji** [comment]
@MainRo Thanks for the detailed explanation. That makes sense :+1:.

**Pull request merged**
